# Generated by Django 6.1 on 2026-08-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product name", models.TextField(max_length=200)),
                ("description", models.TextField(max_length=1000)),
                ("price", models.DecimalField()),
                ("stock", models.PositiveIntegerField()),
                ("image", models.URLField(max_length=500)),
            ],
        ),
    ]
