# Generated by Django 6.1 on 2026-08-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="product name",
            new_name="name",
        ),
    ]
